// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


#include <iostream>
#include <cmath> //for sqrt and ceil

int main() 
{
    int i = 1, j = 2, temp; //first and second term
    int sum = 2;

    do{
        temp = j;
        j += i;
        i = temp;
        if(j % 2 == 0){ sum += j; }
    }while (i <= 4000000 && j <= 4000000);

    printf("%d", sum);
    return 0;
}